export const FETCH_USER_LIST = "FETCH_USER_LIST";
export const FETCH_USERS_NEXT_PAGE = "FETCH_USERS_NEXT_PAGE";

export const FETCH_POINTLOG_LIST = "FETCH_POINTLOG_LIST";
export const ENABLE_POINTLOG_ITEM = "ENABLE_POINTLOG_ITEM";
export const DISABLE_POINTLOG_ITEM = "DISABLE_POINTLOG_ITEM";

export const FETCH_PERSONAL_INFO = "FETCH_PERSONAL_INFO";
export const UPDATE_PERSONAL_INFO = "UPDATE_PERSONAL_INFO";
export const FETCH_POINT_OVERVIEW = "FETCH_POINT_OVERVIEW";
export const FETCH_POINT_LOGS = "FETCH_POINT_LOGS";
export const ENABLE_POINT_LOG = "ENABLE_POINT_LOG";
export const DISABLE_POINT_LOG = "DISABLE_POINT_LOG";
